### ISSUE TITLE
Inaccurate country borders

### ISSUE THREAD

**Issue by kamil-tekiela** [tzhf/get-country-code#1]
I would like to ask whether it would be appreciated if I improved the dataset for country borders. I like the https://mapcheckr.vercel.app/ but when locations are in towns near the border it returns the wrong country name. 
I understand the dataset should be kept as small as possible for performance reasons, but I can see room for improvement in areas with large population and/or major roads. By changing the polygon shapes slightly we could achieve better results. Is this something you would allow me to do? I can fix some borders and submit a PR.

**Comment by tzhf** [comment]
Of course i would, it's a lot of work though ! 
Actually a better option might be to switch to https://github.com/itisem/coordinate_to_country. 

This is what we use for ChatGuessr and it's way more precise.  However precise dataset has performance costs, but i hope it won't make a big difference.

So just a small lib change instead of redrawing polygons seems to be a better option for your time. Performance to be tested though. I let you explore both options !

**Comment by kamil-tekiela** [comment]
Thanks. That's a great idea. I already tested the performance and the impact is unacceptable in my opinion. This dataset is exactly what I was looking for in terms of accuracy, but it's really huge. It crashes my map editor. I am thinking of optimizing this by redrawing the maritime borders, but keeping continental borders intact. I'll see if this improves performance enough. 
However, I noticed one thing: the borders in this repo contain subdivisions of some countries, e.g. Indonesia or UK. The maritime_10m dataset contains only country borders. Would this be acceptable to switch to counting only countries without splitting into subdivisions?

**Comment by tzhf** [comment]
Oh ok, i doubt it would be enough to just redraw the maritime borders as the rest is still pretty well defined
I remember putting a lot of effort in optimizing this one, the performance is more important than the accuracy here as the main purpose is to test a huge batch of coordinates for the mapcheckr, when coordinate_to_country focuses on accuracy.

Then yea if it's still too big feel free to tweak the current geojson then !

About the subdivisions, they are just different polygons at the same level, there's no nesting, so i don't think it really affects the performance, plus it's only for Indo and UK so it's negligible.
